# Generated by Django 6.0 on 2026-01-04 17:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('CHEF', 'Đầu bếp'), ('CUSTOMER', 'Khách hàng')], default='CUSTOMER', max_length=10),
        ),
    ]
