# Generated by Django 6.0 on 2026-01-05 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_user_avatar_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='restaurant/%Y/%m'),
            preserve_default=False,
        ),
    ]
