# Generated by Django 6.0 on 2026-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to='restaurant/%Y/%m'),
        ),
    ]
